### PR TITLE
Add basic Findscript for DepthSense SDK

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

The find script is essentially a modified copy of `FindTinyXml.cmake` from `cmake_modules`. I could've used a random one found on the web, but this one seems to follow 'ROS cmake practices'.

`catkin_lint` outputs a warning about modifying `CMAKE_MODULE_PATH`, but I could not find any better (more catkin-y) way of getting CMake to find a local find script (afaik the script is not needed by dependent pkgs, so `CFG_EXTRAS` doesn't seem right).

---

I've left the `include_directories(..)` statement referencing `suitesparse` in, but commented it. Does not seem to be needed on my machine. I think it can be removed.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Also for #16.

**Comment by gavanderhoorn** [comment]
Ping?

**Comment by corot** [comment]
@ipa-fmw, @ipa-flg, guys, are you still maintaining this code?
I have no problem in doing so, if you are very busy. I must add some improvements to the driver in the following months.

**Comment by abubeck** [comment]
@corrot: I will review and merge the pull requests while @ipa-fmw and @ipa-flg are not available

**Comment by abubeck** [comment]
LGTM but can not be merged anymore after merging other PR's. @gavanderhoorn: can you please update the PR with the upstream changes.
Regarding the additional include: I created issue #21 for @ipa-flg, when he is back.

**Comment by gavanderhoorn** [comment]
I've rebased onto `hydro_dev`, dropping the change to the metapackage manifest.

PR should auto-merge again.

**Pull request merged**
