### PR TITLE
add ROS params to configure depth and color

### PR DESCRIPTION
**Pull request by jordi-pages**
Params to configure depth mode, resolution and rate
Params to configure color compression, resolution and rate
Add specific launch file for the DS311 model as the default configuration works properly for the DS325 model

### CODE REVIEW

**Comment by floweisshardt** [comment]
visual review: OK

**Comment by corot** [comment]
Hi, I tried the pull req code and I got the following errors using the radius filter:

[pcl::OrganizedNeighbor::radiusSearch] Input dataset is not from a projective device!
Residual (MSE) 0.000235, using 1120 valid points
[pcl::OrganizedNeighbor::radiusSearch] Input dataset is not from a projective device!
Residual (MSE) 0.000241, using 1120 valid points
[pcl::OrganizedNeighbor::radiusSearch] Input dataset is not from a projective device!
Residual (MSE) 0.000189, using 1120 valid points
[pcl::OrganizedNeighbor::radiusSearch] Input dataset is not from a projective device!
Residual (MSE) 0.000186, using 1120 valid points
[pcl::OrganizedNeighbor::radiusSearch] Input dataset is not from a projective device!
Residual (MSE) 0.000188, using 1120 valid points
....
Error comes in bursts, and the points and image topics only get published during those bursts.

Without the filter, seems to work fine. I'm using indigo, so maybe it is related with the pcl version. But according to @buihaduong, it doesn't work neither on Hydro. I didn't really try to investigate the error, so excuse me if is something bet I did!

Btw, what are depth_mode close and depth_mode long?

**Comment by buihaduong** [comment]
Hi everyone,

I trying to use depth image data with package depthimage_to_laserscan. 
But it showed this warning:
[ WARN] [1407311794.272714061]: [image_transport] Topics '/softkinetic_camera/depth_registered/image' and '/softkinetic_camera/depth_registered/camera_info' do not appear to be synchronized. In the last 10s:
    Image messages received:      33
    CameraInfo messages received: 0
    Synchronized pairs:           0

So, anyone have any experienced with this problem?

Thanks,
Duong.

**Comment by jordi-pages** [comment]
Hi, I will be out of office until the end of the month so I won't be able
to fix it. I guess that the same timestamp of the camera_info must be set
in the depth image. If somebody can fix it...

**Comment by jordi-pages** [comment]
Hi Jorge. Without the pull request do you get the same error?

Thanks

**Comment by corot** [comment]
no... I have being using the radius filter from the beginning without
problem, so must be something new on the pull req.

2014-08-06 19:24 GMT+02:00 Jordi Pages notifications@github.com:

**Comment by jordi-pages** [comment]
Ok Jorge, thanks for the feedback. I think it is better that the pull
request is rejected and I'll prepare a new one when I am back. Perhaps the
problem is that now the downsampling can be disabled and before it was
always applied when enabling the radius filter.

Regards

**Comment by corot** [comment]
makes sense. without the downsampling the radius filter takes ages (I tried
it out of curiosity)

2014-08-07 15:48 GMT+02:00 Jordi Pages notifications@github.com:

**Comment by buihaduong** [comment]
Hi, I published camera_info data, and senz3d works well with depthimage_to_laserscan package. But the quality is not good. Anyway, thank for your help. :+1:

**Comment by corot** [comment]
Yes, I expected that your laser scan will be too noisy. You could still
improve things by aggressively filtering the depth image, but I would not
expect any miracle.

So how you modified the code? You need to publish the camera_info in a
separated topic?

Could you share the code somehow? I would like to give a try this weekend.

2014-08-07 18:34 GMT+02:00 Bui Ha Duong notifications@github.com:

**Comment by corot** [comment]
I can confirm that this PR works fine if you set use_voxel_grid_filter as true.

**Comment by floweisshardt** [comment]
seems to be stable now. @ipa-flg: please review

**Comment by ipa-flg** [comment]
LGTM :ok_hand:

**Pull request merged**
