### PR TITLE
use memcpy to copy color image instead of nested for-loops

### PR DESCRIPTION
**Pull request by youtalk**
To speed up streaming of color image, this PR uses `std::memcpy` to copy array instead of nested for-loops.

### CODE REVIEW

**Comment by corot** [comment]
:+1: I have included this change also in #30 and I get around ~1.5 Hz faster!
Thanks, @youtalk

**Comment by youtalk** [comment]
@corot Oops, okay I got it.

**Comment by corot** [comment]
No, no!  that was not my intention! This PR is fine because it's over hydro_dev, while mine only affects indigo branch!

Please reopen it!

**Comment by youtalk** [comment]
I see. Anyway, your #30 can be also applied to hydro branch. Hope to merge soon.

**Comment by floweisshardt** [comment]
did this reach consensus to be OK for merge?

**Comment by corot** [comment]
:+1:

**Comment by ipa-flg** [comment]
VR :ok_hand:

**Comment by corot** [comment]
~1.0 Hz faster!

**Comment by youtalk** [comment]
@corot Thank you for merging.

**Pull request merged**
