### PR TITLE
Issue #17: Add color information to published PointCloud2 messages

### PR DESCRIPTION
**Pull request by corot**

### CODE REVIEW

**Comment by corot** [comment]
This PR will interfere with https://github.com/ipa320/softkinetic/pull/22, sorry. If it causes any trouble, please merge first https://github.com/ipa320/softkinetic/pull/22 and I will re-issue this one.

**Comment by floweisshardt** [comment]
@ipa-flg: please review

**Comment by ipa-flg** [comment]
@corot  as #22 is merged, can you please re-issue your request.

**Comment by corot** [comment]
Change included on https://github.com/ipa320/softkinetic/pull/24

**Pull request closed without merging**
