### PR TITLE
fix dynamic_reconfigure config

### PR DESCRIPTION
**Pull request by knorth55**

### CODE REVIEW

**Comment by mgruhler** [comment]
CR: ok

Sorry about the travis integration. This is somehow still active, even though I removed the hook as well as the build in travis... I'll try to sort this out...

**Comment by mgruhler** [comment]
Now... Finally removed properly. This was hidden in the settings...

**Comment by knorth55** [comment]
@ipa-mig thank you so much

**Comment by mgruhler** [comment]
@ipa-flg ping

**Pull request merged**
