### PR TITLE
bring in changes from hydro_dev to indigo_dev

### PR DESCRIPTION
**Pull request by floweisshardt**

### CODE REVIEW

**Comment by ipa-flg** [comment]
:ok_hand:

**Comment by corot** [comment]
mmm...  I'll say that all this changes are already on PR #30. So makes sense mostly to keep a parallel history with hydro branch, right?

Btw, looks like this repo has a lot of contributors but no administrators! Should not another person with more time get merging privileges? (I must say that I have no idea who is/are the administrator(s) now; I hope nobody will take this comment in a bad way)

**Comment by floweisshardt** [comment]
@corot: You're right that we're missing an active maintainer for this repository. Would you like to volunteer for that? If yes, I can add you to the push group so that you can merge pull requests and close issues. Please let me know.

**Comment by corot** [comment]
Sure! I'm quite busy, but not that much that I cannot manage PRs and issues. Thanks.

**Comment by floweisshardt** [comment]
Dear Jorge,
welcome to the push group for ipa320/softkinetic. We normally have the following procedure for merging PRs:
-          There should be at least one review by the repository maintainer who

o   checks that package dependencies are ok

o   checks that package.xml and CMakeLists.txt is filled with reasonable data about author, maintainer, wiki page, install tags, …

o   maintains the repositories meta-package (and adds new packages as dependencies to the meta-package)

o   checks that no unintentionally committed files are in the PR (like ~-Files, .svn, build/, …)
-          There should be at least one review by the package maintainer(s) (all packages that are afftected by the PR). The package maintainers

o   Check the functionality of the code

o   Check the package.xml and CMakeLists.txt is filled with reasonable data about author, maintainer, wiki page, install tags, …

o   No duplicated code is committed but correctly merged
-          It is always ok to merge minor ROS version branches into newer ones, but not the other way round (e.g. merging hydro_dev into indigo_dev is ok, but merging indigo_dev into hydro is NOT ok)

If you need help, please let me know.
Best regards,
Florian

Von: Jorge Santos Simón [mailto:notifications@github.com]
Gesendet: Mittwoch, 1. Oktober 2014 15:25
An: ipa320/softkinetic
Cc: Weißhardt, Florian
Betreff: Re: [softkinetic] bring in changes from hydro_dev to indigo_dev (#33)

Sure! I'm quite busy, but not that much that I cannot manage PRs and issues. Thanks.

**Comment by floweisshardt** [comment]
welcome @corot in the push-group. You should be able to process PRs and issues. Thanks for taking that over.

**Comment by corot** [comment]
Maybe I should have merged this before #30, because now it looks like both branches have diverged for around 30 commits, what it's not true. But it's ok, and the current status is clear:
- hydro_dev is the stable and up to date branch
- indigo_dev is a deep review of the driver with many features and better performance, but not thoroughly tested.

In the mid-term, I would suggest people to move to indigo, as the benefits are notables. Or conversely, reunify both branches and let only the strictly necessary differences, once people have played around enough with the indigo version.

**Comment by floweisshardt** [comment]
@corot: we should try to fix that rather sooner than later. It should always be possible to merge hydro_dev into indigo_dev. There's no need that the branches need to diverge because all indigo specific changes can still be done within the indigo_dev branch. Where as new feature (not API changes) beeing contributed to hydro_dev should find their way easliy to indigo_dev. If you try to sync that manually that will be a lot of overhead.

**Pull request closed without merging**
