### PR TITLE
[indigo_dev] Bring in hydro_dev changes to indigo_dev

### PR DESCRIPTION
**Pull request by floweisshardt**
merging hydro_dev to indigo_dev should be ok to bring in new features and bug fixes.

This can currently not be automatically merged, so please merge manually and resolve merge conflicts.

### CODE REVIEW

**Comment by floweisshardt** [comment]
this solves one part of https://github.com/ipa320/softkinetic/issues/37 (merging hydro changes to indigo)

**Comment by corot** [comment]
Maybe I misunderstood your intention but... why we want to merge hydro into indigo? Indigo already contains all the features of hydro plus many more, so what we gain? Moreover, as @gavanderhoorn stated, merging it will horribly pollute indigo commits history.

Please do not take it bad; I'm not an expert on git, so maybe I'm just missing the point.

**Comment by floweisshardt** [comment]
the point of @gavanderhoorn is that we shouldn't merge h->i and i->h all the time because this will add commits with no content. For automatic maintainability you should do h->i regularly but **not** i->h.

So if you resolve this merge conflict once, the it should be OK for future PRs (h->i) without polluting the history.

**Comment by corot** [comment]
Well... honestly speaking, I still cannot fully see the point of this merge, sorry for my shallow knowledge on git. Anyway, trying to understand your plans better, I have replicated the manual merge in [my own fork](https://github.com/corot/softkinetic):

https://github.com/corot/softkinetic/commit/4903c548d5d27c102f1b717808d92bd67015eefe

As you can see, I did a very expeditive merge: I nearly always retained the indigo version, as the latest and best code.

So now the network looks right, with hydro and indigo merged:

https://github.com/corot/softkinetic/network

I assume that now indigo contains both commits histories, right? Is all this right? Do you want me to do the same on this repo? If so, what would be the next step?

**Comment by floweisshardt** [comment]
your merge looks good. Next step would be that you just send a PR for your merge to indigo_dev (I did that for you in https://github.com/ipa320/softkinetic/pull/43). This PR (#39) should close automatically after #43 is merged.

**Pull request merged**
