### PR TITLE
Add camera description xacro file

### PR DESCRIPTION
**Pull request by corot**
Following discussion on [this ROS answer](http://answers.ros.org/question/190932/creative-senz3d-urdf-or-measurements/)

### CODE REVIEW

**Comment by floweisshardt** [comment]
@ipa-flg: please review

**Comment by ipa-flg** [comment]
@corot  also re-issue please. Good work by the way :+1:

**Comment by corot** [comment]
Ready to merge. Sorry, I changed the install rule on CMakeLists.txt because I'm not sure if the command you used will work for the new directories, so I reverted to the "classic" way.

**Comment by corot** [comment]
Aggg...  stupid me, I forgot I must wait to previous PR getting merged or use a separated branch. So by accident I have accumulated here both PRs. But I'm pretty sure all is fine and can be safely merged.

**Comment by ipa-flg** [comment]
@corot alright, so this also includes #23. Looks good. Thx

**Pull request merged**
